apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: create-pod
  template:
      metadata:
        labels:
          app: create-pod
      spec:
        containers:
        - name: create-pod
          image: gcr.io/level-approach-382012/create-pod:latest
